# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ziusudra/Desktop/aves

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ziusudra/Desktop/aves

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ziusudra/Desktop/aves/CMakeFiles /home/ziusudra/Desktop/aves/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ziusudra/Desktop/aves/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Aves

# Build rule for target.
Aves: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Aves
.PHONY : Aves

# fast build rule for target.
Aves/fast:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/build
.PHONY : Aves/fast

src/Ave.o: src/Ave.cpp.o

.PHONY : src/Ave.o

# target to build an object file
src/Ave.cpp.o:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/Ave.cpp.o
.PHONY : src/Ave.cpp.o

src/Ave.i: src/Ave.cpp.i

.PHONY : src/Ave.i

# target to preprocess a source file
src/Ave.cpp.i:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/Ave.cpp.i
.PHONY : src/Ave.cpp.i

src/Ave.s: src/Ave.cpp.s

.PHONY : src/Ave.s

# target to generate assembly for a file
src/Ave.cpp.s:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/Ave.cpp.s
.PHONY : src/Ave.cpp.s

src/World.o: src/World.cpp.o

.PHONY : src/World.o

# target to build an object file
src/World.cpp.o:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/World.cpp.o
.PHONY : src/World.cpp.o

src/World.i: src/World.cpp.i

.PHONY : src/World.i

# target to preprocess a source file
src/World.cpp.i:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/World.cpp.i
.PHONY : src/World.cpp.i

src/World.s: src/World.cpp.s

.PHONY : src/World.s

# target to generate assembly for a file
src/World.cpp.s:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/World.cpp.s
.PHONY : src/World.cpp.s

src/mainApp.o: src/mainApp.cpp.o

.PHONY : src/mainApp.o

# target to build an object file
src/mainApp.cpp.o:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/mainApp.cpp.o
.PHONY : src/mainApp.cpp.o

src/mainApp.i: src/mainApp.cpp.i

.PHONY : src/mainApp.i

# target to preprocess a source file
src/mainApp.cpp.i:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/mainApp.cpp.i
.PHONY : src/mainApp.cpp.i

src/mainApp.s: src/mainApp.cpp.s

.PHONY : src/mainApp.s

# target to generate assembly for a file
src/mainApp.cpp.s:
	$(MAKE) -f CMakeFiles/Aves.dir/build.make CMakeFiles/Aves.dir/src/mainApp.cpp.s
.PHONY : src/mainApp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Aves"
	@echo "... src/Ave.o"
	@echo "... src/Ave.i"
	@echo "... src/Ave.s"
	@echo "... src/World.o"
	@echo "... src/World.i"
	@echo "... src/World.s"
	@echo "... src/mainApp.o"
	@echo "... src/mainApp.i"
	@echo "... src/mainApp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

